# yaml-language-server: $schema=https://raw.githubusercontent.com/BeatSketch/launcher/refs/heads/main/config.schema.json

cleanup:
  collisions: false
  distance: false
default_save_path: ~/BeatSketch/
folder_loc_for_picker: ~/Downloads/
mirror: false
saber_angle:
  x: -20
  y: 0
  z: 0
used_model: mlp_torch
vibrate: false
