# yaml-language-server: $schema=config.schema.json

cleanup:
  collisions: false
  distance: false
default_save_path: "~"
folder_loc_for_picker: ~/Downloads/
mirror: false
saber_angle:
  x: -20
  y: 0
  z: 0
used_model: mlp_torch
vibrate: false
